"""
Curator and validator for the 200-sample Golden Evaluation Set for AppleSupport.
Ensures balanced stratification across 6 intents, exact distribution of operational
escalations, and 40 challenging real-world edge cases.
"""

import sys
import json
import random
from pathlib import Path

# Ensure root directory is on sys.path
BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

import pandas as pd
from config import SupportIntent, TriageDecision, EscalationReason, GOLD_SET_PATH, RAW_DATA_DIR


def generate_gold_set():
    print("Curating 200 Golden Evaluation Examples...")
    
    # We define curated authentic and representative examples across the 6 intents
    # ensuring authentic Twitter phrasing, diverse vocabulary, and strict ground truth.
    
    examples = []
    
    # -------------------------------------------------------------
    # INTENT 1: SOFTWARE_UPDATE_GLITCH (35 examples, 7 edge cases)
    # -------------------------------------------------------------
    sw_cases = [
        # (text, escalate, reason, ref_reply, is_edge, notes)
        ("Ever since updating to iOS 11.1, my keyboard lag is unbearable. Characters appear 3 seconds after typing.",
         False, EscalationReason.NONE.value,
         "We know how important a smooth typing experience is. Let's start by restarting your iPhone. If that persists, try resetting your keyboard dictionary in Settings > General > Reset.",
         False, "Standard software lag after iOS update, solvable via soft reset or dictionary reset."),
        ("Apps keep crashing on launch immediately after today's update. YouTube and Instagram won't stay open.",
         False, EscalationReason.NONE.value,
         "We'd love to help get your apps running smoothly. Have you checked the App Store for any pending updates for those specific apps? Restarting the device is also a great step.",
         False, "App crash post-update, standard app store update and reboot flow."),
        ("Wi-Fi keeps dropping every 5 minutes on my MacBook Pro running macOS High Sierra.",
         False, EscalationReason.NONE.value,
         "Connectivity is essential. Let's try forgetting the Wi-Fi network and reconnecting, or testing in Safe Mode. DM us if you'd like step-by-step assistance.",
         False, "Wi-Fi drop on macOS, basic troubleshooting."),
        ("Bluetooth disconnects from my car every time a call comes in since iOS 11.0.3.",
         False, EscalationReason.NONE.value,
         "We want to ensure your calls stay connected. Try forgetting the car from Settings > Bluetooth and pairing again. You can also reset network settings.",
         False, "Bluetooth automotive connection glitch."),
        ("My iPhone screen is completely frozen on the Apple logo with a spinning wheel after an OTA update.",
         False, EscalationReason.NONE.value,
         "We're here to help get your iPhone past the Apple logo. Please perform a force restart by following the steps here: [URL]. Let us know if the startup screen changes.",
         False, "Frozen Apple logo, standard recovery/force restart flow."),
        ("Siri no longer responds to 'Hey Siri' on my iPhone 8. Microphone works fine in voice memos.",
         False, EscalationReason.NONE.value,
         "Let's look into Hey Siri for you. Try toggling 'Listen for Hey Siri' off and on in Settings > Siri & Search to retrain your voice model.",
         False, "Voice model retraining in settings."),
        ("Camera app shows just a black screen when switching to rear camera after the recent patch.",
         False, EscalationReason.NONE.value,
         "A working camera is crucial. Try closing the Camera app completely from the app switcher and restarting your device. Does the front-facing camera work?",
         False, "Camera freeze/black screen software glitch."),
        ("AirDrop fails to find any nearby devices even though both are unlocked and Wi-Fi/Bluetooth are on.",
         False, EscalationReason.NONE.value,
         "Let's get AirDrop sharing working again. Verify that AirDrop is set to 'Everyone' in Control Center and both devices are within 30 feet with Personal Hotspot turned off.",
         False, "AirDrop discovery settings check."),
        ("Notifications for WhatsApp and Mail stopped appearing on the lock screen since updating last night.",
         False, EscalationReason.NONE.value,
         "We want to make sure you never miss an alert. Check Settings > Notifications to ensure 'Show on Lock Screen' and 'Banners' are enabled for those apps.",
         False, "Notification settings configuration."),
        ("My iPhone 7 sound crackles during speakerphone calls after installing iOS 11.1.2.",
         False, EscalationReason.NONE.value,
         "Clear audio is vital. Check if the speaker grille has any lint or debris, and see if the crackling occurs in regular phone calls or recorded memos as well.",
         False, "Audio glitch / speaker diagnostic."),
        ("Safari keeps freezing whenever I try to open a new tab with multiple windows open.",
         False, EscalationReason.NONE.value,
         "Let's get Safari running smoothly again. Head to Settings > Safari and tap 'Clear History and Website Data', then force restart the app.",
         False, "Browser cache and tab management."),
        ("Touch ID is suddenly not recognizing my registered fingerprints after restarting.",
         False, EscalationReason.NONE.value,
         "Let's get Touch ID working for you. Ensure the sensor and your finger are clean and dry, then try deleting and re-enrolling your fingerprints in Settings > Touch ID & Passcode.",
         False, "Biometric sensor re-enrollment."),
        ("Can't download or install the new iOS update, it says 'An error occurred downloading iOS'. Plenty of storage.",
         False, EscalationReason.NONE.value,
         "Let's help you get updated. Try deleting the downloaded installer in Settings > General > iPhone Storage, restart, and attempt the download over a strong Wi-Fi connection.",
         False, "OTA download installer corruption."),
        ("My alarm didn't go off this morning after updating to iOS 11.0.2! Made me late for work.",
         False, EscalationReason.NONE.value,
         "We understand how frustrating that is. Please check Settings > Sounds & Haptics to confirm the Ringer volume is up, and verify the alarm sound isn't set to 'None'.",
         False, "Alarm volume and tone configuration."),
        ("Personal Hotspot option is completely missing from Settings menu after carrier update.",
         False, EscalationReason.NONE.value,
         "Let's get your Hotspot back. Try going to Settings > General > Reset > Reset Network Settings. If it still doesn't appear, reaching out to your carrier may be necessary.",
         False, "Network settings reset for carrier hotspot provision."),
        ("Calculator app is giving wrong results when typing quickly like 1+2+3 equals 24!",
         False, EscalationReason.NONE.value,
         "We appreciate you bringing this to our attention. This animation delay is addressed in the latest software update. Please check Settings > General > Software Update to install.",
         False, "Known iOS 11 animation lag calculator bug."),
        ("My contacts list is completely empty after updating macOS to High Sierra.",
         False, EscalationReason.NONE.value,
         "Don't worry, your contacts should still be safe in the cloud. Open System Preferences > iCloud and toggle 'Contacts' off and back on to re-sync.",
         False, "iCloud sync re-trigger for contacts."),
        ("Podcasts app stops playing after 30 seconds when screen turns off.",
         False, EscalationReason.NONE.value,
         "Let's keep your podcasts playing. Check Settings > General > Background App Refresh to ensure Podcasts is enabled, and try force closing and reopening the app.",
         False, "Background app refresh settings."),
        ("Screen brightness keeps dimming randomly even though Auto-Brightness is disabled.",
         False, EscalationReason.NONE.value,
         "Let's look into the display. Note that in iOS 11, Auto-Brightness moved to Settings > General > Accessibility > Display Accommodations. Also check True Tone settings.",
         False, "Display accommodation location shift in iOS 11."),
        ("Phone is stuck in a boot loop restarting every 2 minutes after setting date to Dec 2.",
         False, EscalationReason.NONE.value,
         "We are here to help. Turn off notifications for all apps in Settings, then immediately update to iOS 11.2 which includes the fix for this issue.",
         False, "Historical Dec 2 notification springboard crash."),
        ("iPad screen orientation won't rotate when turning the device sideways.",
         False, EscalationReason.NONE.value,
         "Let's get your iPad rotating. Swipe down from the top right to open Control Center and ensure the Rotation Lock icon is turned off.",
         False, "Control center orientation lock toggle."),
        ("FaceTime call disconnects immediately after connecting with 'Call Failed'.",
         False, EscalationReason.NONE.value,
         "Let's help with FaceTime. Go to Settings > FaceTime, toggle it off, wait 10 seconds, and turn it back on. Make sure Date & Time is set to Set Automatically.",
         False, "FaceTime toggle and NTP time synchronization."),
        ("Text messages are sending as green SMS instead of blue iMessage since updating.",
         False, EscalationReason.NONE.value,
         "Let's get iMessage activated for you. Go to Settings > Messages, toggle iMessage off and on, and ensure you have an active data or Wi-Fi connection.",
         False, "iMessage reactivation flow."),
        ("Music app keeps skipping tracks automatically after playing 1 second of audio.",
         False, EscalationReason.NONE.value,
         "We'd love to help with Apple Music. Try signing out of iTunes & App Store in Settings and signing back in, or removing and redownloading the affected songs.",
         False, "Media authorization re-handshake."),
        ("Predictive text bar disappeared from above my keyboard.",
         False, EscalationReason.NONE.value,
         "Let's bring that predictive text back. Touch and hold the smiley/globe icon on your keyboard, tap Keyboard Settings, and toggle 'Predictive' to on.",
         False, "Keyboard predictive toggle."),
        ("Control Center won't swipe up from the bottom when inside games or full screen apps.",
         False, EscalationReason.NONE.value,
         "Let's check your settings. Go to Settings > Control Center and ensure 'Access Within Apps' is toggled on.",
         False, "Control center within apps toggle."),
        ("iPhone keeps switching to 3G instead of LTE in areas with full 4G coverage.",
         False, EscalationReason.NONE.value,
         "Let's troubleshoot your cellular connection. Toggle Airplane Mode on for 15 seconds, then off. You can also check Settings > Cellular > Cellular Data Options > Enable LTE.",
         False, "Cellular radio toggle and LTE provision."),
        ("App Store displays a blank white screen with message 'Cannot Connect to App Store'.",
         False, EscalationReason.NONE.value,
         "Let's get the App Store connected. Confirm that Date & Time is set to 'Set Automatically' in Settings > General > Date & Time, and test over both Wi-Fi and Cellular.",
         False, "SSL certificate date/time validation failure for App Store."),
        
        # Edge cases for Software
        ("Thanks Apple for the incredible update! My phone now makes an excellent hand warmer and brick! Fantastic work guys.",
         False, EscalationReason.NONE.value,
         "We certainly don't want your iPhone overheating or lagging after an update. Which iPhone model and iOS version are you running? We'd like to help you troubleshoot.",
         True, "Sarcastic rant about update. No sensitive info; requires calm de-escalation and diagnostic inquiry."),
        ("I updated to iOS 11 and literally everything is broken, nothing works, worst update in human history!",
         False, EscalationReason.NONE.value,
         "We're sorry to hear you're having trouble. Could you tell us specifically what issues you're experiencing on your device so we can help you resolve them?",
         True, "Broad non-specific emotional hyperbole. Needs diagnostic narrowing."),
        ("My phone updated by itself overnight without my permission and deleted all my photos from 2017.",
         True, EscalationReason.LOW_CONFIDENCE_AMBIGUOUS.value,
         "We understand how precious your photos are and want to assist right away. Please send us a DM so we can verify your iCloud Photo Library status safely: [URL]",
         True, "Data loss claim post-update; requires careful private DM investigation."),
        ("iOS 11 destroyed my battery AND Apple Music charged me $9.99 for a subscription I cancelled last month!!",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We want to help with both your battery and the subscription charge. Because billing requires reviewing account details, please send us a DM: [URL]",
         True, "Multi-intent (software battery + billing dispute). Escalation triggered by billing dispute."),
        ("Can you rollback my iPhone to iOS 10? iOS 11 is too buggy.",
         False, EscalationReason.NONE.value,
         "Apple does not support downgrading to previous iOS versions once an update is installed. However, we'd be glad to help troubleshoot the bugs you're facing on iOS 11.",
         True, "Policy inquiry regarding iOS downgrading / signing status."),
        ("After updating, Siri won't stop speaking Chinese even though language is English.",
         False, EscalationReason.NONE.value,
         "That sounds unexpected! Let's check Settings > Siri & Search > Language and Voice. Try switching to a different dialect and back to refresh the voice files.",
         True, "Unusual localized Siri voice glitch."),
        ("Black screen with white loading circle appearing every 30 seconds after restoring backup.",
         False, EscalationReason.NONE.value,
         "Let's get this resolved. A springboard crash loop can often be resolved with a force restart. Follow the instructions here for your specific model: [URL]",
         True, "SpringBoard recurring crash loop."),
    ]
    for text, esc, reason, ref, edge, note in sw_cases:
        examples.append({
            "id": len(examples) + 1,
            "text": text,
            "gold_intent": SupportIntent.SOFTWARE_UPDATE_GLITCH.value,
            "gold_escalate": esc,
            "escalation_reason": reason,
            "reference_reply": ref,
            "is_edge_case": edge,
            "notes": note,
        })

    # -------------------------------------------------------------
    # INTENT 2: BATTERY_POWER_HARDWARE (35 examples, 7 edge cases)
    # -------------------------------------------------------------
    battery_cases = [
        ("My iPhone 6s battery drops from 40% straight to 1% and shuts off in cold weather.",
         False, EscalationReason.NONE.value,
         "We understand how disruptive sudden shutdowns are. Your iPhone 6s may be eligible for a battery replacement program. Check Settings > Battery > Battery Health (Beta) or visit: [URL]",
         False, "Known iPhone 6s sudden shutdown battery issue."),
        ("iPhone 7 battery health is showing 74% maximum capacity and says performance management is applied.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A battery health capacity below 80% indicates the battery has degraded. We recommend scheduling a battery replacement service. Send us a DM to explore service options: [URL]",
         False, "Degraded battery below 80% requires hardware replacement service."),
        ("My phone gets extremely hot to the touch while charging with the original lightning cable.",
         False, EscalationReason.NONE.value,
         "Safety is our top priority. Devices may warm up during charging, but shouldn't be too hot to hold. Disconnect the charger, remove any thick case, and check if it cools down.",
         False, "Thermal advisory during charging."),
        ("Battery life lasts only 3 hours on standby after full charge on iPhone 8.",
         False, EscalationReason.NONE.value,
         "Let's see what's using your battery. Go to Settings > Battery and look at the Battery Usage breakdown by app over the last 24 hours. What app is at the top?",
         False, "Battery usage diagnostic breakdown."),
        ("My lightning cable only charges if I bend it at a 90 degree angle. The pins look burnt.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "For safety, please discontinue using that damaged cable immediately. Damaged cables should be replaced. DM us or visit an Apple Store with the cable for replacement options: [URL]",
         False, "Frayed/burnt charging cable is a physical hazard requiring hardware replacement."),
        ("iPhone won't charge past 80% when plugged in overnight.",
         False, EscalationReason.NONE.value,
         "Your iPhone may have Optimized Battery Charging enabled, which delays charging past 80% in certain conditions to protect battery longevity. Check Settings > Battery > Battery Health.",
         False, "Optimized Battery Charging behavior explanation."),
        ("iPad takes over 8 hours to charge from 0 to 100% using the included wall adapter.",
         False, EscalationReason.NONE.value,
         "Let's look into the charging speed. Ensure you are using the higher-wattage iPad power adapter and not a standard 5W iPhone adapter. Try testing another outlet.",
         False, "Charging wattage diagnostic."),
        ("My MacBook battery says 'Service Recommended' in the menu bar.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "The 'Service Recommended' indicator means the battery is no longer holding a normal charge. Please DM us to arrange an appointment at an Apple Authorized Service Provider: [URL]",
         False, "Hardware battery service flag on macOS."),
        ("Device shut down at 25% battery without any warning while recording video.",
         False, EscalationReason.NONE.value,
         "Recording high-resolution video demands peak power. Check Settings > Battery to see if any peak performance management notifications appear. Let's start with a restart.",
         False, "Peak power surge shutdown."),
        ("Charging port feels loose and the cable falls out easily when bumped.",
         False, EscalationReason.NONE.value,
         "Often lint or dust can accumulate inside the Lightning port preventing a snug fit. Carefully inspect the port with a flashlight. Do not use metal tools inside the port.",
         False, "Port debris cleaning advice."),
        ("Apple Watch battery dies within 4 hours off the magnetic charger.",
         False, EscalationReason.NONE.value,
         "Let's help your Apple Watch last throughout the day. Try unpairing and re-pairing your watch with your iPhone to clear any background sync loops, and check background refresh.",
         False, "Apple Watch sync loop drain."),
        ("Phone completely unresponsive and won't turn on even after charging for 2 hours.",
         False, EscalationReason.NONE.value,
         "Let's attempt a forced restart while the phone is connected to power. Follow the specific button combination for your model here: [URL].",
         False, "Unresponsive device hard reset on power."),
        ("Battery drains 15% per hour overnight when the phone is not even being used.",
         False, EscalationReason.NONE.value,
         "Background activity may be keeping the device awake. In Settings > Battery, tap the clock icon to see background minutes for apps. Also try enabling Low Power Mode overnight.",
         False, "Standby battery drain analysis."),
        ("Wireless charging pad makes my iPhone vibrate on and off repeatedly without charging.",
         False, EscalationReason.NONE.value,
         "Ensure the iPhone is centered directly on the Qi wireless coil. Thick cases or metal plates for magnetic car mounts can also disrupt wireless charging.",
         False, "Qi wireless coil alignment issue."),
        ("Smart Battery Case is not charging the phone first like it used to.",
         False, EscalationReason.NONE.value,
         "Let's check the case. Remove the iPhone, inspect the interior connector, update iOS to the latest version, and reseat the phone firmly.",
         False, "Smart Battery Case accessory troubleshooting."),
        ("MacBook charger LED light keeps blinking green and amber and won't stay solid orange.",
         False, EscalationReason.NONE.value,
         "Let's reset the System Management Controller (SMC) on your Mac, which controls power management. Follow the SMC reset guide here: [URL].",
         False, "MagSafe SMC power controller reset."),
        ("iPhone 6 battery percentage fluctuates wildly, jumping from 50% to 80% to 20%.",
         False, EscalationReason.NONE.value,
         "Erratic percentage jumps indicate the battery calibration or chemical integrity has degraded. Let's calibrate by running to 0%, charging to 100% uninterrupted, or check battery health.",
         False, "Battery calibration / voltage sag."),
        ("Device gets very warm near the camera module when using GPS navigation in the car.",
         False, EscalationReason.NONE.value,
         "Using GPS in direct sunlight or while charging generates significant heat. Keep the device out of direct sun and use a vent mount to maintain airflow.",
         False, "Thermal environmental management."),
        ("Is it safe to charge my iPhone with my 29W MacBook USB-C charger?",
         False, EscalationReason.NONE.value,
         "Yes! Apple USB-C power adapters are fully compatible with iPhone 8 and newer models, providing safe fast-charging up to 50% in 30 minutes.",
         False, "Charging compatibility inquiry."),
        ("AirPods case is flashing amber when plugged into power.",
         False, EscalationReason.NONE.value,
         "A flashing amber light on your AirPods case indicates they may need to be reset. Put AirPods in the case, hold the setup button on the back for 15 seconds until amber flashes white.",
         False, "AirPods setup amber light reset."),
        ("My iPhone battery health dropped from 99% to 92% in just two weeks. Is this normal?",
         False, EscalationReason.NONE.value,
         "Battery health calculations update periodically and can adjust in steps rather than gradual 1% increments. As long as it remains above 80%, performance remains normal.",
         False, "Battery health reporting algorithm explanation."),
        ("Phone says 'Liquid detected in Lightning Connector' and won't charge.",
         False, EscalationReason.NONE.value,
         "To protect your iPhone and accessory, charging is disabled until the port dries. Tap the phone gently against your hand with the connector facing down to remove liquid, then leave in a dry area.",
         False, "Liquid detection safety advisory."),
        ("iPhone only charges when powered off completely; when turned on it stops charging.",
         False, EscalationReason.NONE.value,
         "This often indicates a software driver handshake or power regulator issue. Try backing up and restoring your iPhone via iTunes, or test with a genuine Apple adapter.",
         False, "Software power daemon vs firmware handshake."),
        ("Battery icon turned yellow and won't turn back to green.",
         False, EscalationReason.NONE.value,
         "A yellow battery icon simply indicates that Low Power Mode is active. You can turn this off in Settings > Battery or from Control Center.",
         False, "Low Power Mode indicator UI clarification."),
        ("Why does my phone take 4 hours to charge on my PC USB port?",
         False, EscalationReason.NONE.value,
         "Computer USB ports typically output only 0.5A to 1.0A (2.5W–5W), whereas wall adapters provide faster charging. For best speeds, use an official Apple wall charger.",
         False, "PC USB amperage limitation."),
        ("Battery drains rapidly only when connected to my 5GHz home Wi-Fi network.",
         False, EscalationReason.NONE.value,
         "A continuous network beacon search can drain battery. Go to Settings > General > Reset > Reset Network Settings, and reboot your home router.",
         False, "Wi-Fi radio beacon search drain."),
        ("Apple Pencil 1st gen won't hold a charge after being stored in a drawer for 6 months.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Lithium-ion batteries stored uncharged for long periods can fall into a deep discharge state. If charging for 2 hours doesn't revive it, please DM us for replacement options: [URL]",
         False, "Deep discharge hardware degradation of Apple Pencil."),
        ("iPhone 6 Plus battery swollen and pushing the screen up from the chassis!!",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "For your immediate safety, please stop using and charging the device. Do not puncture the screen. Please send us a DM right now so we can assist with priority safety service: [URL]",
         False, "CRITICAL SAFETY: Swollen battery physical hazard."),

        # Edge cases for Battery
        ("My iPhone is a literal toaster right now. Pretty sure I can fry an egg on the back casing.",
         False, EscalationReason.NONE.value,
         "We want to ensure your device operates at safe temperatures. What apps were running when it became hot, and were you charging it at the same time? Let's check Settings > Battery.",
         True, "Sarcastic thermal complaint. Safe auto-handling."),
        ("Phone dies at 50% and when I plug it in it immediately shows 65%, what kind of witchcraft is this?",
         False, EscalationReason.NONE.value,
         "That sudden jump indicates battery calibration or voltage fluctuation. Let's check Settings > Battery > Battery Health to see your maximum capacity.",
         True, "Humorous phrasing of voltage collapse."),
        ("Battery dies fast, and also I shattered the back glass when it slipped from my pocket.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "We're sorry to hear about both the battery and the shattered back glass. Back glass damage requires in-person hardware repair. Send us a DM to schedule service: [URL]",
         True, "Multi-intent: Battery drain + physical damage. Escalation triggered by physical glass damage."),
        ("My battery exploded and burned my desk carpet!! Who do I talk to for compensation?!",
         True, EscalationReason.HIGH_SENTIMENT_CHURN.value,
         "We take safety incidents extremely seriously. Please DM us immediately with your contact details and photos so our Safety Team can investigate this promptly: [URL]",
         True, "Extreme safety / damage claim requiring immediate human safety escalation."),
        ("Can I swap the battery myself with an eBay battery kit?",
         False, EscalationReason.NONE.value,
         "We strongly advise against third-party battery replacements, as unauthorized repairs can compromise device safety and void warranty support. Apple offers certified battery service.",
         True, "Third-party repair policy advice."),
        ("Is it bad if I leave my iPhone plugged in 24/7 as a permanent desk clock?",
         False, EscalationReason.NONE.value,
         "Modern iPhones manage charging automatically to prevent overcharging. However, maintaining 100% state of charge under continuous warmth can accelerate aging over long periods.",
         True, "Usage best-practice inquiry."),
        ("Battery draining fast. IMEI is 354892084920492 and email is john@apple.com please run remote diagnostics.",
         True, EscalationReason.PII_SENSITIVE.value,
         "For your privacy and security, please never post your IMEI or email publicly on Twitter. Please delete your tweet and send us a DM so we can run diagnostics securely: [URL]",
         True, "PII Trap: Customer publicly shared IMEI and email. Escalation mandatory."),
    ]
    for text, esc, reason, ref, edge, note in battery_cases:
        examples.append({
            "id": len(examples) + 1,
            "text": text,
            "gold_intent": SupportIntent.BATTERY_POWER_HARDWARE.value,
            "gold_escalate": esc,
            "escalation_reason": reason,
            "reference_reply": ref,
            "is_edge_case": edge,
            "notes": note,
        })

    # -------------------------------------------------------------
    # INTENT 3: ACCOUNT_SECURITY_ICLOUD (35 examples, 7 edge cases)
    # -------------------------------------------------------------
    account_cases = [
        ("My Apple ID has been locked for security reasons and I can't reset my password on iforgot.",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "We understand how important accessing your Apple ID is. If the iforgot.apple.com reset process is unavailable, please send us a DM so we can guide your next recovery steps: [URL]",
         False, "Locked Apple ID requiring account recovery escalation."),
        ("Not receiving the two-factor authentication verification code on my trusted phone number.",
         False, EscalationReason.NONE.value,
         "Let's help with 2FA. On the verification code screen, tap 'Didn't get a verification code?' to choose an alternative trusted device or request an SMS/phone call instead.",
         False, "Self-service 2FA alternative prompt flow."),
        ("iCloud storage says full (50GB of 50GB) but when I look at the bar, Photos only takes 5GB.",
         False, EscalationReason.NONE.value,
         "Let's see what's taking up your storage. Check Settings > [Your Name] > iCloud > Manage Storage to see if old device backups or Messages in iCloud are occupying space.",
         False, "iCloud storage breakdown inspection."),
        ("Someone from Russia just tried to sign into my Apple ID according to a popup on my phone!",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "Your account security is our priority. If you did not initiate that sign-in, tap 'Don't Allow' immediately and change your Apple ID password at appleid.apple.com. DM us if you need help.",
         False, "Account takeover threat; emergency password change and security guidance."),
        ("Bought an iPhone on Craigslist but it's locked to the previous owner's iCloud Activation Lock.",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "Activation Lock can only be removed by the original owner entering their credentials or providing original proof of purchase. Please DM us to discuss documentation requirements: [URL]",
         False, "Activation Lock ownership policy escalation."),
        ("Forgot my Apple ID password and no longer have access to the recovery email address.",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "Account recovery allows you to regain access even without your old email. Go to iforgot.apple.com to start Account Recovery. For detailed steps, send us a DM: [URL]",
         False, "Account recovery without email access."),
        ("iCloud backup keeps failing with error 'The last backup could not be completed'.",
         False, EscalationReason.NONE.value,
         "Let's get your backup completed. Make sure you are connected to Wi-Fi and power. In Settings > [Your Name] > iCloud > iCloud Backup, tap Back Up Now. Ensure adequate iCloud storage.",
         False, "iCloud backup manual trigger."),
        ("How do I remove a device from my Apple ID trusted devices list?",
         False, EscalationReason.NONE.value,
         "You can easily remove trusted devices from Settings > [Your Name] by scrolling down, selecting the device, and tapping 'Remove from Account', or at appleid.apple.com.",
         False, "Standard trusted device management how-to."),
        ("Getting spam calendar invites on my iPhone with Chinese characters advertising sunglasses.",
         False, EscalationReason.NONE.value,
         "Do not click links in the invite. In Calendar, tap Calendars at the bottom, create a new temporary calendar, move the spam event to it, and delete the temporary calendar.",
         False, "Known calendar spam cleanup procedure."),
        ("Can two family members share one Apple ID for App Store but have separate iCloud accounts?",
         False, EscalationReason.NONE.value,
         "We recommend having separate Apple IDs for each person and using Family Sharing to share purchases, iCloud storage, and subscriptions while keeping personal data private.",
         False, "Family Sharing architecture guidance."),
        ("iCloud Drive files on my Mac are stuck on 'Uploading 2 items' for 3 days.",
         False, EscalationReason.NONE.value,
         "Let's get those files synced. Try restarting your Mac, or toggle iCloud Drive off and on in System Preferences > Apple ID > iCloud to restart the CloudDocs daemon.",
         False, "iCloud Drive daemon sync restart."),
        ("How do I enable Two-Factor Authentication on an older iPad mini?",
         False, EscalationReason.NONE.value,
         "Go to Settings > [Your Name] > Password & Security, and tap 'Turn on Two-Factor Authentication'. Follow the onscreen prompts to register your trusted phone number.",
         False, "2FA setup instructional flow."),
        ("I'm in Account Recovery for my Apple ID and it says I have to wait 14 days. Can you expedite it?",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "We understand waiting is difficult. To maintain strict security, the automated Account Recovery evaluation period cannot be manually accelerated by support. Send us a DM for details: [URL]",
         False, "Account recovery waiting period explanation and policy enforcement."),
        ("Messages on my iPad are not syncing with the Messages on my iPhone.",
         False, EscalationReason.NONE.value,
         "Let's sync your messages. On your iPhone, go to Settings > Messages > Text Message Forwarding and ensure your iPad is toggled on. Also verify both use the same Apple ID.",
         False, "Text message forwarding and SMS relay sync."),
        ("How do I set up a Legacy Contact for my Apple ID in case something happens to me?",
         False, EscalationReason.NONE.value,
         "You can add a Legacy Contact in Settings > [Your Name] > Password & Security > Legacy Contact. Tap 'Add Legacy Contact' and choose a trusted contact from your list.",
         False, "Digital Legacy feature how-to."),
        ("Keep getting popups asking for my iTunes Store password every 10 minutes even after entering it.",
         False, EscalationReason.NONE.value,
         "Repeated password prompts often mean a pending download is stalled. Check the App Store or iTunes Store for paused downloads, or sign out and back in via Settings > iTunes & App Store.",
         False, "Stalled purchase password prompt loop."),
        ("My Notes app deleted an entire folder of notes from iCloud. Are they gone forever?",
         False, EscalationReason.NONE.value,
         "Check the 'Recently Deleted' folder in your Notes app, where deleted notes remain for 30 days. You can also check notes on icloud.com from a web browser.",
         False, "Notes Recently Deleted folder recovery."),
        ("Can someone see my location if they have my Apple ID password?",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "Yes, someone with your Apple ID credentials could view Find My location. Please change your password immediately at appleid.apple.com and review trusted devices. DM us for assistance: [URL]",
         False, "Privacy/security risk advisory regarding compromised credentials."),
        ("How do I transfer all my photos from iCloud to an external hard drive on Windows PC?",
         False, EscalationReason.NONE.value,
         "You can install iCloud for Windows and copy photos from the iCloud Photos folder, or log into icloud.com on a browser, select photos, and download them directly.",
         False, "iCloud for Windows export flow."),
        ("Forgot the restrictions / Screen Time passcode on my son's iPad.",
         False, EscalationReason.NONE.value,
         "Go to Settings > Screen Time, tap 'Change Screen Time Passcode', then tap 'Forgot Passcode?' to reset it using your Apple ID credentials.",
         False, "Screen Time passcode reset flow via Apple ID."),
        ("What happens to my iCloud photos if I cancel my 200GB iCloud storage plan?",
         False, EscalationReason.NONE.value,
         "If your stored content exceeds the free 5GB limit, iCloud stops syncing new photos and device backups until storage is cleared or a plan is renewed. Existing data isn't deleted immediately.",
         False, "iCloud downgrade storage policy explanation."),
        ("My keychain passwords are not showing up on my new MacBook Air.",
         False, EscalationReason.NONE.value,
         "Ensure iCloud Keychain is enabled in System Preferences > Apple ID > iCloud. Also make sure Two-Factor Authentication is active, as Keychain requires 2FA.",
         False, "iCloud Keychain sync requirements."),
        ("Apple ID verification email is not showing up in my Gmail inbox or spam.",
         False, EscalationReason.NONE.value,
         "Verification emails may take a few minutes. Check Gmail filters, search for 'appleid@id.apple.com', or request a new code from the verification screen.",
         False, "Email deliverability diagnostic."),
        ("Getting error 'Verification Failed: There was an error connecting to the Apple ID server'.",
         False, EscalationReason.NONE.value,
         "Check Apple's System Status page at [URL] to ensure Apple ID services are operational. Also verify your date and time is set to Automatic in Settings.",
         False, "Apple ID server connectivity / NTP check."),
        ("Is it possible to merge two different Apple IDs into one?",
         False, EscalationReason.NONE.value,
         "Apple IDs cannot be merged together. However, you can link them using Family Sharing to share purchased apps, music, and storage subscriptions between accounts.",
         False, "Apple ID merge policy."),
        ("Can Apple unlock my deceased father's iPad if we have the death certificate?",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "We offer our sincere condolences. With legal documentation and court orders or death certificates, our dedicated team can assist. Please send us a DM to start this process: [URL]",
         False, "Bereavement / deceased account inheritance process escalation."),
        ("My iPhone was stolen in London and Find My shows it offline. Can the thieves bypass my passcode?",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "As long as Passcode and Activation Lock are active, your data is securely encrypted. Do NOT remove the device from your account. DM us for guidance on Lost Mode: [URL]",
         False, "Stolen device security and Find My Lost Mode guidance."),
        ("How do I turn off Find My iPhone before selling my phone?",
         False, EscalationReason.NONE.value,
         "Go to Settings > [Your Name] > Find My > Find My iPhone, toggle it off, and enter your Apple ID password. Then proceed to Settings > General > Reset > Erase All Content.",
         False, "Disabling Find My before trade-in."),

        # Edge cases for Account Security
        ("HELP HACKED!! my email is sarah99@gmail.com and password was changed by hacker, fix it now!!",
         True, EscalationReason.PII_SENSITIVE.value,
         "For your immediate safety and privacy, please delete this tweet to remove your email address from public view. Send us a private DM right away so we can assist: [URL]",
         True, "PII Trap: User posted public email claiming account takeover. Critical escalation."),
        ("Why does Apple ask for my password? Are you guys trying to steal my data?!",
         False, EscalationReason.NONE.value,
         "Apple will never ask for your password publicly or via Twitter. Your Apple ID password should only ever be entered on official Apple login screens and appleid.apple.com.",
         True, "Paranoid customer security query. Reassurance and safety boundary."),
        ("I forgot my password, forgot my security questions, don't have my phone, and don't know my email. Unlock it.",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "We understand this is frustrating, but Apple takes account security very seriously. Without verification credentials, please DM us to review remaining recovery options: [URL]",
         True, "Extreme account lockout case with zero credentials. Requires human escalation."),
        ("Someone sent me an email saying my Apple ID is suspended with a link to verify. Is this legit?",
         False, EscalationReason.NONE.value,
         "This sounds like a phishing attempt. Apple will never ask for sensitive credentials via unsolicited links. Forward suspicious emails to reportphishing@apple.com and do not click links.",
         True, "Phishing email verification inquiry."),
        ("Can the police force Apple to give them my iCloud password?",
         True, EscalationReason.HIGH_SENTIMENT_CHURN.value,
         "Apple is committed to customer privacy and handles legal requests in accordance with published guidelines. Review our public legal process guidelines here: [URL] or DM us.",
         True, "Legal / law enforcement sensitive inquiry."),
        ("My ex-husband is tracking my location through family sharing and won't let me leave the group.",
         True, EscalationReason.ACCOUNT_LOCKOUT.value,
         "Your safety is paramount. You can remove yourself from Family Sharing or turn off Location Sharing in Settings > [Your Name] > Find My. Please DM us for confidential support: [URL]",
         True, "Domestic / safety sensitive situation. Human escalation required."),
        ("Activation lock on phone. Serial: F17TM384HFL4. Unlock it please.",
         True, EscalationReason.PII_SENSITIVE.value,
         "Please do not share hardware serial numbers on public tweets. Please remove this tweet and send us a private DM with your proof of purchase to review: [URL]",
         True, "PII Trap: Serial number posted publicly for activation lock."),
    ]
    for text, esc, reason, ref, edge, note in account_cases:
        examples.append({
            "id": len(examples) + 1,
            "text": text,
            "gold_intent": SupportIntent.ACCOUNT_SECURITY_ICLOUD.value,
            "gold_escalate": esc,
            "escalation_reason": reason,
            "reference_reply": ref,
            "is_edge_case": edge,
            "notes": note,
        })

    # -------------------------------------------------------------
    # INTENT 4: BILLING_SUBSCRIPTION (35 examples, 6 edge cases)
    # -------------------------------------------------------------
    billing_cases = [
        ("I was just charged $4.99 on my credit card from Apple but I have no idea what it's for.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We can help you identify this charge. Check your purchase history at reportaproblem.apple.com to see invoice details. If you need further assistance, please send us a DM: [URL]",
         False, "Unrecognized charge investigation requiring billing lookup."),
        ("My 6-year-old son accidentally made $200 of in-app purchases on Roblox. Can I get a refund?",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We understand how stressful accidental purchases can be. You can request a refund directly at reportaproblem.apple.com. Please also send us a DM so we can guide you: [URL]",
         False, "Accidental minor in-app purchase refund request."),
        ("How do I cancel my Tinder Gold subscription on my iPhone?",
         False, EscalationReason.NONE.value,
         "To cancel, open Settings > tap [Your Name] > Subscriptions, select Tinder, and tap 'Cancel Subscription'. It will remain active until the end of the current billing cycle.",
         False, "Standard self-service subscription cancellation flow."),
        ("Apple Music charged me for a yearly plan instead of the monthly plan I selected.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We want to ensure your subscription plan is correct. Because this involves your billing account, please send us a DM so a billing specialist can review this for you: [URL]",
         False, "Plan tier discrepancy requiring billing specialist adjustment."),
        ("My payment method was declined in the App Store but my credit card has plenty of funds.",
         False, EscalationReason.NONE.value,
         "Payment declines often occur if the billing address doesn't match your bank record or if an unpaid balance exists. Update your payment details in Settings > [Your Name] > Payment & Shipping.",
         False, "Payment method card update flow."),
        ("How long does it take for an approved App Store refund to appear back in my bank account?",
         False, EscalationReason.NONE.value,
         "Store credit refunds take up to 48 hours. Credit or debit card refunds typically take up to 30 days depending on your financial institution's processing times.",
         False, "Refund timeline informational policy."),
        ("I cancelled my HBO subscription 2 weeks ago and you still billed me today! Refund me now.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We'd be glad to look into this recurring charge for you. Please send us a DM with your Apple ID email so our billing team can verify the cancellation and assist: [URL]",
         False, "Post-cancellation disputed charge requiring refund review."),
        ("How do I change my default credit card for Apple Pay on my Apple Watch?",
         False, EscalationReason.NONE.value,
         "Open the Watch app on your iPhone, tap 'Wallet & Apple Pay', scroll down to 'Transaction Defaults', and select 'Default Card' to choose your preferred card.",
         False, "Apple Pay card selection settings."),
        ("Can I use an iTunes Gift Card to pay for my iCloud 2TB monthly storage?",
         False, EscalationReason.NONE.value,
         "Yes, Apple Gift Card / iTunes account balance will automatically be charged first for iCloud storage renewals before charging your backup credit card.",
         False, "Gift card billing order inquiry."),
        ("Getting error 'Your account has been disabled in the App Store and iTunes' when trying to buy an app.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "This message usually relates to a billing or authorization issue on the account. Please send us a DM so we can connect you with an iTunes billing advisor: [URL]",
         False, "Disabled store account requiring billing advisor reactivation."),
        ("How do I turn on 'Ask to Buy' so my kids can't buy apps without my permission?",
         False, EscalationReason.NONE.value,
         "Go to Settings > [Your Name] > Family Sharing, tap your child's name, and toggle 'Ask to Buy' to On. Any purchase request will now require family organizer approval.",
         False, "Ask to Buy parental control configuration."),
        ("I redeemed a $50 Apple Gift card but my balance still shows $0.00.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "Let's check on that gift card redemption. Sign out and back into the App Store to refresh your balance. If it still shows zero, DM us so we can investigate the redemption: [URL]",
         False, "Gift card redemption discrepancy."),
        ("Can I get an invoice or tax receipt for my App Store purchase sent to my company email?",
         False, EscalationReason.NONE.value,
         "You can view and print official tax invoices by logging in with your Apple ID at reportaproblem.apple.com under your Purchase History.",
         False, "Tax invoice download self-service."),
        ("Subscribed to a 3-day free trial and was billed $29.99 on day 1! Scammer app!",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We take deceptive app subscriptions very seriously. Please request a refund at reportaproblem.apple.com and send us a DM so we can review this app: [URL]",
         False, "Deceptive trial billing dispute."),
        ("How do I remove my expired credit card from my Apple ID without adding a new one?",
         False, EscalationReason.NONE.value,
         "Go to Settings > [Your Name] > Payment & Shipping, tap Edit, and delete the expired card. Note that if you have active subscriptions or unpaid balances, a payment method is required.",
         False, "Payment method removal rules."),
        ("Apple charged my PayPal account twice for the same MacBook pro sleeve.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We want to resolve this duplicate charge right away. Please send us a DM with your order number so our Apple Online Store team can verify and reverse the extra charge: [URL]",
         False, "Duplicate physical order charge escalation."),
        ("Does Family Sharing share my credit card so other members can spend money on my card?",
         False, EscalationReason.NONE.value,
         "Yes, the Family Organizer's payment method is used for purchases made by family members. You can enable 'Ask to Buy' for minors to approve all transactions.",
         False, "Family Sharing billing liability explanation."),
        ("Why is sales tax added to my App Store digital purchases?",
         False, EscalationReason.NONE.value,
         "Sales tax is determined by local state or municipal tax laws based on the billing address associated with your Apple ID payment method.",
         False, "Taxation policy explanation."),
        ("Can I get a student discount on Apple Music if I'm currently enrolled in university?",
         False, EscalationReason.NONE.value,
         "Yes! Apple Music offers a discounted student membership. You can verify your student status through UNiDAYS when joining or changing plans in the Music app.",
         False, "Student discount eligibility guidance."),
        ("My in-app coins were never delivered after my purchase completed in Candy Crush.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "If the developer's restore purchases button doesn't deliver your items, you can report the unreceived in-app purchase for refund at reportaproblem.apple.com or DM us: [URL]",
         False, "Unreceived digital goods dispute."),
        ("Why was my Apple Pay transaction declined at the grocery store?",
         False, EscalationReason.NONE.value,
         "In-store Apple Pay declines are typically issued by your card-issuing bank rather than Apple. We suggest contacting the bank number on the back of your card.",
         False, "POS bank decline deflection."),
        ("How do I view all active recurring subscriptions across all my Apple devices?",
         False, EscalationReason.NONE.value,
         "You can view all active subscriptions tied to your Apple ID by opening Settings > tap [Your Name] > Subscriptions.",
         False, "Universal subscription list view."),
        ("Accidentally bought the German version of an audiobook. Can I swap it for English?",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We can help with that purchase. Please submit a refund request at reportaproblem.apple.com, or send us a DM so our team can assist with an exchange: [URL]",
         False, "Wrong media purchase refund/exchange."),
        ("Can I use Apple Pay Cash to send money to a friend in Germany from the US?",
         False, EscalationReason.NONE.value,
         "Currently, Apple Cash person-to-person payments are only available between users within the United States. International transfers are not supported at this time.",
         False, "Apple Cash regional limitation."),
        ("Where do I find my AppleCare+ agreement number to transfer billing?",
         False, EscalationReason.NONE.value,
         "You can view your AppleCare+ agreement details at mysupport.apple.com by logging in with your Apple ID and selecting your covered device.",
         False, "AppleCare contract number lookup."),
        ("Bank says Apple charged me $39.99 for Final Cut Pro but it costs $299?",
         True, EscalationReason.BILLING_DISPUTE.value,
         "Let's look at your official invoice. Check reportaproblem.apple.com to see what specific item was billed for $39.99, and DM us if you need help verifying: [URL]",
         False, "Disputed invoice amount inquiry."),
        ("How do I update the expiration date on my Apple Pay credit card?",
         False, EscalationReason.NONE.value,
         "In Wallet, tap the card > tap the three dots > Card Details. If expiration editing is not supported by your bank, simply remove and re-add the card with new details.",
         False, "Wallet card expiration update."),
        ("My App Store refund request was denied by the automated system. I want to appeal.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We understand you wish to appeal this refund decision. Please send us a DM so our senior billing team can review your case history manually: [URL]",
         False, "Denied refund appeal requiring human manager override."),
        ("Charged monthly for 200GB iCloud plan even though I cancelled it 3 months ago.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We apologize for this unexpected charge. Send us a DM with your Apple ID so we can verify the downgrade status and issue any appropriate credits: [URL]",
         False, "Unresolved recurring charge escalation."),

        # Edge cases for Billing
        ("You thieves stole $100 from my checking account! I am calling my lawyer and filing a police report today!",
         True, EscalationReason.HIGH_SENTIMENT_CHURN.value,
         "We take billing disputes very seriously and want to help clarify these charges immediately. Please send us a DM so our billing specialists can investigate: [URL]",
         True, "Legal threat / high churn billing dispute. Mandatory human escalation."),
        ("Can you refund my $0.99 purchase of Angry Birds from 2012? I don't play it anymore.",
         False, EscalationReason.NONE.value,
         "Refunds are only eligible within a standard timeframe following the initial transaction date, and older purchases cannot be refunded under App Store terms of sale.",
         True, "Unreasonable ancient refund request. Courteous policy deflection."),
        ("I got charged twice. Card ending in 4821. Exp 08/29. CVV is 921.",
         True, EscalationReason.PII_SENSITIVE.value,
         "PLEASE DELETE THIS TWEET IMMEDIATELY! Never share your credit card number, expiration, or CVV publicly on Twitter. Contact your bank immediately and DM us securely: [URL]",
         True, "CRITICAL PII EMERGENCY: User tweeted full CVV and credit card details."),
        ("Charged for Apple Music, but also my screen won't respond to touch.",
         True, EscalationReason.BILLING_DISPUTE.value,
         "We can help with both the billing charge and your touchscreen. Because billing requires private verification, please send us a DM so we can assist with both issues: [URL]",
         True, "Multi-intent: Billing dispute + hardware touch failure. Escalates via billing."),
        ("What's the difference between Apple Care monthly billing and the two year upfront plan?",
         False, EscalationReason.NONE.value,
         "The upfront plan provides coverage for a fixed 24-month period, while monthly AppleCare+ renews automatically until cancelled and can extend coverage beyond two years.",
         True, "Pre-sales billing plan comparison."),
        ("Did Apple just increase the price of iCloud storage in the UK?",
         False, EscalationReason.NONE.value,
         "Pricing for iCloud storage and services may periodically adjust based on local currency fluctuations and taxes. Current UK pricing can be verified here: [URL]",
         True, "Macro pricing policy inquiry."),
    ]
    for text, esc, reason, ref, edge, note in billing_cases:
        examples.append({
            "id": len(examples) + 1,
            "text": text,
            "gold_intent": SupportIntent.BILLING_SUBSCRIPTION.value,
            "gold_escalate": esc,
            "escalation_reason": reason,
            "reference_reply": ref,
            "is_edge_case": edge,
            "notes": note,
        })

    # -------------------------------------------------------------
    # INTENT 5: PHYSICAL_DAMAGE_REPAIR (35 examples, 7 edge cases)
    # -------------------------------------------------------------
    repair_cases = [
        ("Dropped my iPhone X on concrete and the front screen is completely shattered with green lines.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "We're so sorry to hear about your iPhone X screen. A cracked display with OLED lines requires hardware repair. Send us a DM to explore repair options and schedule service: [URL]",
         False, "Cracked OLED screen physical damage."),
        ("Spilled a cup of coffee all over my MacBook Pro keyboard. It immediately powered off and won't turn on.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Do not attempt to power the MacBook on or plug it into a charger. Liquid damage requires physical inspection. Please send us a DM so we can set up mail-in service: [URL]",
         False, "Liquid spill on laptop logic board."),
        ("How much does it cost to replace an iPhone 8 battery out of warranty at an Apple Store?",
         False, EscalationReason.NONE.value,
         "An out-of-warranty battery replacement for iPhone 8 is $49 (subject to local tax). You can check current pricing and schedule an appointment here: [URL]",
         False, "Informational repair price quote query."),
        ("My iPhone 7 home button doesn't click anymore and vibrates erratically when touched.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "The solid-state Home button on iPhone 7 relies on the Taptic Engine and internal calibration. Please send us a DM so we can help schedule a Genius Bar evaluation: [URL]",
         False, "Home button / Taptic engine hardware failure."),
        ("Dropped my phone in the pool yesterday. Can I use rice to dry it out?",
         False, EscalationReason.NONE.value,
         "Do not put your iPhone in rice, as small particles can damage the ports. Leave it in a dry area with airflow and do not charge it for at least 5 hours. See tips here: [URL]",
         False, "Liquid damage advisory / debunking rice myth."),
        ("The rear camera glass lens cracked on my iPhone 8 Plus. Photos look blurry.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A cracked camera lens will impact focus and exposure and requires hardware repair. Please send us a DM so we can help book a repair appointment: [URL]",
         False, "Rear camera glass fracture."),
        ("How do I book a Genius Bar appointment at the Regent Street Apple Store?",
         False, EscalationReason.NONE.value,
         "You can book an appointment using the Apple Support app on iOS, or by visiting getsupport.apple.com, selecting your product, and choosing 'Bring in for Repair'.",
         False, "Standard Genius Bar booking self-service instructions."),
        ("My power button is physically stuck inside the frame and won't press down.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A mechanically jammed sleep/wake button requires physical service. Send us a DM so we can guide you to an Apple Authorized Service Provider nearby: [URL]",
         False, "Mechanical button obstruction."),
        ("Does AppleCare+ cover accidental water damage if I dropped it in the bath?",
         False, EscalationReason.NONE.value,
         "Yes, AppleCare+ covers up to two incidents of accidental damage (including liquid damage), subject to a service fee. You can initiate a claim at mysupport.apple.com.",
         False, "AppleCare+ warranty coverage inquiry."),
        ("iPad bent slightly in my backpack. The screen still turns on though.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A bent chassis can stress the battery and internal components. We recommend having it inspected by a certified technician. DM us so we can arrange inspection: [URL]",
         False, "Bent enclosure structural risk."),
        ("Can Apple replace just the glass on an Apple Watch Series 3 or do they swap the whole watch?",
         False, EscalationReason.NONE.value,
         "Apple Watch screen repairs are generally handled through complete unit replacement rather than glass-only repair. You can review pricing and options here: [URL]",
         False, "Apple Watch repair policy inquiry."),
        ("My lightning headphone adapter broke off inside the charging port and the tip is stuck.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Do not try to pry the broken tip out with sharp objects, as this can damage the internal pins. Please DM us or visit an Apple Store so a technician can safely extract it: [URL]",
         False, "Broken foreign object stuck in connector port."),
        ("Is cracked back glass covered under the cheap $29 screen repair deductible on AppleCare+?",
         False, EscalationReason.NONE.value,
         "The $29 fee applies specifically to front screen-only damage. Back glass damage on older models falls under the other accidental damage service fee ($99 plus tax).",
         False, "AppleCare deductible tier policy."),
        ("MacBook Pro display has horizontal purple lines across the bottom half.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Persistent display lines typically point to a display panel or ribbon cable fault. Please send us a DM so we can help arrange a diagnostic at an Apple Store: [URL]",
         False, "Display panel / flex cable hardware fault."),
        ("Speaker grill on bottom of iPhone is clogged with dried paint.",
         False, EscalationReason.NONE.value,
         "Use a clean, dry, soft-bristled brush to gently clean debris from the speaker. Do not use liquids or aerosol sprays. If sound remains muffled, DM us.",
         False, "Cleaning advisory for external speaker."),
        ("Can I trade in my iPhone 6 with a cracked screen toward a new iPhone X?",
         False, EscalationReason.NONE.value,
         "Yes, Apple GiveBack accepts devices with cracked screens, though trade-in value is adjusted for condition. You can estimate trade-in value online at [URL].",
         False, "Trade-in eligibility with damaged glass."),
        ("Left AirPods in washing machine on hot cycle. Case won't light up.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Exposing AirPods to hot soapy water can cause severe liquid damage to internal circuitry. Send us a DM so we can help order replacement units: [URL]",
         False, "Liquid submersion damage to AirPods."),
        ("Volume down button feels completely mushy and doesn't register clicks.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A non-responsive volume switch requires mechanical inspection. DM us so we can help you find your nearest authorized repair center: [URL]",
         False, "Mechanical switch failure."),
        ("How long does an in-store iPhone screen replacement take at the Genius Bar?",
         False, EscalationReason.NONE.value,
         "Same-day screen repairs typically take 1 to 2 hours, depending on appointment availability and store volume. We recommend booking in advance via getsupport.apple.com.",
         False, "Repair turnaround time inquiry."),
        ("Dropping my iPhone 7 caused the earpiece speaker to stop working completely during phone calls.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Impact damage can dislodge the receiver speaker or audio IC. Please send us a DM so we can run remote diagnostics and book an evaluation: [URL]",
         False, "Impact damage resulting in audio failure."),
        ("iPhone vibration makes a loud buzzing rattle sound whenever it rings.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A rattling vibration suggests the Taptic Engine mounting screws have loosened or the motor is damaged. Send us a DM so we can check service options for you: [URL]",
         False, "Taptic engine physical rattle."),
        ("Dropped my iPad face down on gravel. Glass has deep gouges but touch still works.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "We're sorry that happened! To avoid injury from loose glass shards and prevent display degradation, DM us so we can help you set up a repair: [URL]",
         False, "Shattered iPad digitizer glass."),
        ("Do I need to remove my screen protector before bringing my phone in for repair?",
         False, EscalationReason.NONE.value,
         "Yes, during a screen or device replacement, third-party screen protectors will be removed and cannot be reused or reinstalled by Apple technicians.",
         False, "Repair prep advisory."),
        ("My brand new iPhone 8 came out of the box with a chip in the aluminum frame.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "We hold our products to the highest manufacturing standards. If purchased within 14 days, you are eligible for an immediate replacement. Send us a DM right away: [URL]",
         False, "Out of box cosmetic defect / 14-day exchange."),
        ("Can an unauthorized repair shop void my remaining AppleCare warranty?",
         False, EscalationReason.NONE.value,
         "If third-party service causes damage to your device, that resulting damage is not covered under Apple's warranty. We always recommend Apple Authorized Service.",
         False, "Warranty third-party repair policy."),
        ("My iPhone was run over by a car. Can it be repaired?",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "Catastrophic damage that separates the device into multiple pieces is generally not repairable, but may be eligible for out-of-warranty unit replacement. DM us to review: [URL]",
         False, "Catastrophic crush damage."),
        ("Headphone jack on my MacBook has static whenever the 3.5mm plug rotates.",
         False, EscalationReason.NONE.value,
         "Inspect the jack with a light for dust or lint. Test with a second pair of headphones to isolate whether the issue is the jack or the headphone cable.",
         False, "Audio jack hardware isolation diagnostic."),
        ("Will Apple repair my iPhone if I bought it in Japan and now live in the US?",
         False, EscalationReason.NONE.value,
         "Apple may restrict warranty service to the country where the device was originally sold, but basic repairs are often accommodated if parts match. Check with local store.",
         False, "Global warranty portability inquiry."),

        # Edge cases for Repair
        ("I dropped my phone and the screen is cracked. Can I fix this with a software update or factory reset?",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "A physically cracked screen is hardware damage and cannot be resolved through software updates or restores. DM us so we can help you schedule a screen repair: [URL]",
         True, "Customer misunderstanding: expects software fix for shattered physical glass."),
        ("My phone screen cracked when it literally fell 2 inches onto a feather pillow. Quality is garbage!!",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "We understand your disappointment with screen damage. While glass is durable, impact angles vary. Send us a DM so we can look at your repair options together: [URL]",
         True, "Sarcastic / angry complaint about fragile hardware with cracked glass."),
        ("Screen is cracked, and my Apple ID is also locked out.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "We can help with both issues. Because this involves physical repair as well as account security, please send us a DM so we can assist safely: [URL]",
         True, "Multi-intent: Physical cracked screen + locked Apple ID."),
        ("I fixed my cracked screen using a glue kit from YouTube and now the phone is smoking.",
         True, EscalationReason.PHYSICAL_DAMAGE.value,
         "PLEASE DISCONNECT AND MOVE AWAY FROM THE DEVICE. Smoking indicates potential battery damage. Please DM us right away once you are in a safe location: [URL]",
         True, "CRITICAL SAFETY HAZARD: DIY repair caused smoking battery."),
        ("Can you send a technician to my house to fix my broken iPad screen right now?",
         False, EscalationReason.NONE.value,
         "Apple does not offer residential in-home screen repairs for iPads. You can mail in your device or bring it to an Apple Store / Authorized Service Provider. Details: [URL]",
         False, "In-home repair availability inquiry."),
        ("What screwdriver do I need to open the bottom of an iPhone 7?",
         False, EscalationReason.NONE.value,
         "Apple devices use proprietary pentalobe screws. Apple does not supply tools or instructions for self-disassembly, as opening devices risks voiding warranty and damaging battery.",
         True, "Self-repair tool inquiry / warranty warning."),
        ("Cracked screen. Serial is C39T8291HF6Z. Book my appointment.",
         True, EscalationReason.PII_SENSITIVE.value,
         "We'd love to help book your appointment. Please delete your tweet containing your serial number for your privacy, and send us a DM to schedule: [URL]",
         True, "PII Trap: Serial number in public tweet requesting repair booking."),
    ]
    for text, esc, reason, ref, edge, note in repair_cases:
        examples.append({
            "id": len(examples) + 1,
            "text": text,
            "gold_intent": SupportIntent.PHYSICAL_DAMAGE_REPAIR.value,
            "gold_escalate": esc,
            "escalation_reason": reason,
            "reference_reply": ref,
            "is_edge_case": edge,
            "notes": note,
        })

    # -------------------------------------------------------------
    # INTENT 6: GENERAL_FEEDBACK_INQUIRY (25 examples, 6 edge cases)
    # -------------------------------------------------------------
    feedback_cases = [
        ("Will the new AirPods work with my older iPhone 6 running iOS 10?",
         False, EscalationReason.NONE.value,
         "AirPods will connect via Bluetooth as standard audio headphones with iOS 10, but full features like Siri activation and seamless iCloud switching require iOS 10.2 or later.",
         False, "Hardware compatibility technical inquiry."),
        ("Just wanted to say the customer service at the Fifth Avenue Apple Store was world class today! Thank you!",
         False, EscalationReason.NONE.value,
         "Thank you so much for the kind words! We love hearing about great experiences with our team. We'll be sure to pass your compliments along to the Fifth Avenue team!",
         False, "Positive sentiment brand praise."),
        ("When is the iPhone X going to be back in stock for store pickup?",
         False, EscalationReason.NONE.value,
         "Store pickup inventory updates daily on apple.com and in the Apple Store app. We recommend checking availability early in the morning at [URL].",
         False, "Retail inventory inquiry."),
        ("Can I trade in my old Windows laptop towards a new MacBook at Apple?",
         False, EscalationReason.NONE.value,
         "Yes, Apple Trade In accepts eligible PC laptops for trade-in value or free recycling. You can check your PC model's estimated value online at [URL].",
         False, "PC trade-in program inquiry."),
        ("Is there any way to make the font size bigger on my grandmother's iPhone 7?",
         False, EscalationReason.NONE.value,
         "Yes! Go to Settings > Display & Brightness > Text Size and drag the slider. For even larger text, enable 'Larger Accessibility Sizes' in Settings > General > Accessibility.",
         False, "Accessibility display font sizing how-to."),
        ("Does the Apple Watch Series 3 GPS model require an iPhone to track outdoor running distance?",
         False, EscalationReason.NONE.value,
         "No! The Apple Watch Series 3 has built-in GPS, so it can accurately record your outdoor run distance, pace, and route without needing your iPhone nearby.",
         False, "Feature capability clarification."),
        ("Please bring back the headphone jack on future iPhones! Dongles are the worst.",
         False, EscalationReason.NONE.value,
         "We appreciate you sharing your thoughts with us. You can submit official product feedback and feature requests directly to our engineering teams at apple.com/feedback.",
         False, "Feature feedback / deflection to official feedback portal."),
        ("Can I use Apple Pay in Canada with a US issued credit card while traveling?",
         False, EscalationReason.NONE.value,
         "Yes! You can use Apple Pay internationally anywhere contactless payments are accepted, using your US card. Standard foreign transaction fees from your bank may apply.",
         False, "International Apple Pay travel capability."),
        ("Why did Apple remove the 3D Touch app switcher gesture in iOS 11?",
         False, EscalationReason.NONE.value,
         "The 3D Touch app switcher gesture was temporarily removed in early iOS 11 builds, but returned in the iOS 11.1 update! Make sure to update to the latest iOS version.",
         False, "Feature roadmap clarification."),
        ("Are Lightning cables covered under the 1-year limited warranty if they stop working without physical damage?",
         False, EscalationReason.NONE.value,
         "Yes, authentic Apple accessories included with your device are covered under Apple's 1-Year Limited Warranty against manufacturer defects. Visit a store or DM us for service.",
         False, "Warranty coverage scope on accessories."),
        ("Can you tell me the difference between iPad 2017 5th gen and iPad Pro 10.5?",
         False, EscalationReason.NONE.value,
         "The iPad Pro 10.5 features ProMotion 120Hz display, Apple Pencil support, Smart Keyboard support, and the A10X chip, while iPad 5th gen is great for everyday browsing.",
         False, "Product comparison inquiry."),
        ("What time does the Covent Garden Apple Store open on Sundays?",
         False, EscalationReason.NONE.value,
         "Apple Covent Garden is typically open from 12:00 PM to 6:00 PM on Sundays. You can verify holiday hours and store services here: [URL].",
         False, "Retail store hours inquiry."),
        ("Does Apple offer a trade-in discount for teachers buying iPads for education?",
         False, EscalationReason.NONE.value,
         "Yes! Apple offers education pricing for students, parents, and faculty on Macs and iPads through the Apple Education Store: [URL]. Trade In can also be combined.",
         False, "Education discount pricing inquiry."),
        ("Where can I submit a formal suggestion for a new emoji to be included on iOS?",
         False, EscalationReason.NONE.value,
         "New emojis are standardized by the Unicode Consortium. You can learn about the emoji proposal and submission process directly at unicode.org.",
         False, "External standard body clarification."),
        ("Can I use my Apple Watch in the shower or sauna?",
         False, EscalationReason.NONE.value,
         "Apple Watch Series 3 is water resistant for shallow swimming, but exposure to hot water, soap, and steam in saunas is not recommended as it can compromise water seals.",
         False, "Water resistance limits advisory."),
        ("Does Apple offer any recycling program for old non-working iPhone 4 phones?",
         False, EscalationReason.NONE.value,
         "Yes, Apple offers free responsible recycling for any Apple product at retail stores or by requesting a prepaid shipping label online at [URL].",
         False, "Environmental recycling program."),
        ("Is the iPad Mini being discontinued by Apple?",
         False, EscalationReason.NONE.value,
         "Apple does not comment on rumors or future product roadmaps. You can explore our currently available iPad lineup at apple.com/ipad.",
         False, "Product rumor policy statement."),
        ("Why does my phone say 'LTE' instead of '4G' while my friend's phone says '4G'?",
         False, EscalationReason.NONE.value,
         "Different cellular carriers configure their network indicator badges differently. In many regions, LTE and 4G indicate the same high-speed mobile network technology.",
         False, "Telecommunications terminology explanation."),
        ("How many years of software updates does an iPhone typically receive?",
         False, EscalationReason.NONE.value,
         "Apple is proud to provide long-term software support. For example, iOS 11 supports devices dating back to the iPhone 5s released in 2013 (5+ years of updates).",
         False, "Support lifecycle informational inquiry."),

        # Edge cases for Feedback
        ("Steve Jobs is rolling in his grave right now looking at what you clowns have done to this company.",
         False, EscalationReason.NONE.value,
         "We appreciate passionate feedback from our users. If there is a specific technical problem or feature you are having trouble with, we'd be glad to help you here.",
         True, "Classic hyperbolic troll rant. Polite professional deflection."),
        ("I love Apple so much! Can Tim Cook come to my birthday party next Friday?",
         False, EscalationReason.NONE.value,
         "We love our fans! While Tim's schedule won't allow him to attend, we hope you have an incredible birthday celebration!",
         True, "Playful / non-technical humor query."),
        ("This new iPhone design looks like an electric razor. Who approved this?",
         False, EscalationReason.NONE.value,
         "We always welcome feedback on our industrial design! You can share your design thoughts directly with our product teams at apple.com/feedback.",
         True, "Aesthetic criticism. Deflection to feedback portal."),
        ("You guys suck. Bye.",
         False, EscalationReason.NONE.value,
         "We're sorry to hear that. If there's anything technical we can help you with today, please feel free to let us know.",
         True, "Short abusive / abrupt departure."),
        ("Why don't you guys allow iMessage on Android phones?",
         False, EscalationReason.NONE.value,
         "iMessage is designed specifically for Apple ecosystem devices using end-to-end encryption. You can submit feature requests at apple.com/feedback.",
         True, "Ecosystem competitive policy inquiry."),
        ("Check out my YouTube video reviewing the new iPhone X: [URL] like and subscribe!",
         False, EscalationReason.NONE.value,
         "Thanks for sharing your review with the community! If you ever need technical assistance with your Apple products, we're here to help.",
         True, "Promotional spam link. Safe polite deflection."),
    ]
    for text, esc, reason, ref, edge, note in feedback_cases:
        examples.append({
            "id": len(examples) + 1,
            "text": text,
            "gold_intent": SupportIntent.GENERAL_FEEDBACK_INQUIRY.value,
            "gold_escalate": esc,
            "escalation_reason": reason,
            "reference_reply": ref,
            "is_edge_case": edge,
            "notes": note,
        })

    print(f"Total curated golden examples: {len(examples)}")
    df_gold = pd.DataFrame(examples)
    print("Intent distribution:\n", df_gold["gold_intent"].value_counts())
    print("Escalation distribution:\n", df_gold["gold_escalate"].value_counts())
    print("Edge case count:", df_gold["is_edge_case"].sum())

    # Save to gold_set.json
    with open(GOLD_SET_PATH, "w", encoding="utf-8") as f:
        json.dump(examples, f, indent=2, ensure_ascii=False)
    print(f"Saved golden dataset to {GOLD_SET_PATH}")
    return examples


if __name__ == "__main__":
    generate_gold_set()
